Onenot/learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('learning_logs.urls',namespace='learning_logs'))
]

Onenot/learning_logs/urls.py
"""Определяет схемы URL для learning_logs"""
from django.conf.urls import url
from . import views  # импортируем из каталога файл

app_name = 'learning_log'
urlpatterns = [  # список страниц которые могут запрашиваться из приложения learning_logs
    # Домашняя страница
    url(r'^$', views.index, name='index'),
    # 2-ой аргумент определяет ф-ю представления нашей страницы, 3-й аргумент определяет index для этой схемы URL что-бы можно было ссылаться в других частях кода
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    # Символ r сообщает Django, что последующая строка должна интерпретироваться без дополнительной обработки, а выражение заключено в кавычки. Вторая часть выражения, /(?P<topic_id>\d+)/, описывает целое число, заключенное между двумя косыми чертами; это целое число сохраняется в аргументе topic_id. Круглые скобки, в которые заключена эта часть выражения, сохраняют значение из URL; часть ?P<topic_id> сохраняет совпавшее значение в topic_id; а выражение \d+ совпадает с любым количеством цифр, заключенных между символами косой черты.
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url(r'^del_topic/(?P<topic_id>\d+)/$', views.del_topic, name='del_topic'),
    url(r'^del_entry/(?P<entry_id>\d+)/$', views.del_entry, name='del_entry'),

]

Onenot/learning_logs/models.py
from django.db import models


# Create your models here.
class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()  # create an unlimited text field

    date_added = models.DateTimeField(
        auto_now_add=True)  # select the records in the order they were created and mark each record with a timestamp
    class Meta:
        verbose_name_plural = 'entries'  # When referring to more than one entry we use the plural form entries
    def __str__(self):
        """Возвращает строковое представление модели"""
        if len(self.text) < 50:
            return self.text[:50]
        else:
            return self.text[:50] + "..."

Onenot/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):  # Простейшая версия ModelForm состоит из вложенного класса Meta, который сообщает
    # Django, на какой модели должна базироваться форма и какие поля на ней должны находиться.
    class Meta:
        model = Topic  # форма создается на базе модели Topic, а на ней размещается только поле text
        fields = ['text']
        labels = {'text': ''}  # не генерировать подпись для текстового поля.


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}  # Включая атрибут widgets, вы можете переопределить
        # виджеты, выбранные Django по умолчанию. Приказывая Django использовать элемент forms.Textarea, мы настраиваем
        # виджет ввода для поля 'text', чтобы ширина текстовой области составляла 80 столбцов вместо значения по умолчанию 40.

Onenot/learning_logs/views.py
from django.shortcuts import render  # ф-я возвращает html шаблон
from .models import Topic, Entry
from django.http import HttpResponseRedirect  # перенаправляет
# пользователя к странице topics после отправки введенной темы.
from django.http import HttpResponseNotFound
from django.urls import reverse  # Функция reverse() определяет URL
# по заданной схеме URL (то есть Django сгенерирует URL при запросе страницы).
from .forms import TopicForm, EntryForm


# Create your views here.
def index(request):
    """Домашняя сираница предложения learning log"""
    return render(request, 'learning_logs/index.html')  # Функция render() использует два аргумента — исходный объект
    # запроса и шаблон, используемый для построения страницы.


def topics(request):
    """Выводит списиок тем"""
    topics = Topic.objects.order_by()
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Выводит одну запись и все ее записи"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':  # При построении веб-приложений используются два основных типа запросов — GET и POST. Запросы GET используются для страниц, которые только читают данные с сервера, а запросы POST обычно используются в тех случаях, когда пользователь должен отправить информацию через форму
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(request.POST)  # в request.POST хранятся данные передаваемые пользователем
        if form.is_valid():  # is_valid()-проверяет чтобы все поля были заполнены
            form.save()  # записывает данные из формы в базу и сохраняет
            return HttpResponseRedirect(reverse('learning_logs:topics'))  # Мы используем вызов reverse() для получения
            # URL-адреса страницы topics и передаем его функции HttpResponseRedirect()
            # , перенаправляющей браузер пользователя на страницу topics.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()  # создаем пустой экземпляр
    else:
        form = EntryForm(data=request.POST)  # создавая экземпляр EntryForm, заполненный данными POST из объекта запроса
        if form.is_valid():
            new_entry = form.save(commit=False)  # создаем новый объект записи и сохранить его в new_entry, не сохраняя
            # пока в базе данных
            new_entry.topic = topic  # Мы присваиваем атрибуту topic объекта new_entry тему, прочитанную из базы данных
            # в начале функции, после чего вызываем save() без аргументов.
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)  # получаем объект записи, который пользователь хочет изменить, и тему,
    # связанную с этой записью.
    topic = entry.topic
    if request.method != 'POST':
        form = EntryForm(instance=entry)  # (instance=entry) - приказывает Django создать форму,
        # заранее заполненную информацией из существующего объекта записи
    else:
        form = EntryForm(instance=entry, data=request.POST)  # При обработке запроса POST передаются аргументы
        # instance=entry и data=request.POST , чтобы приказать Django создать экземпляр формы на основании
        # информации существующего объекта записи, обновленный данными из request.POST
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


def del_topic(request, topic_id):
    try:
        topic = Topic.objects.get(id=topic_id)
        topic.delete()
        return HttpResponseRedirect(reverse('learning_logs:topics'))
    except Topic.DoesNotExist:
        return HttpResponseNotFound("Topic not exist")


def del_entry(request, entry_id):
    try:
        entry = Entry.objects.get(id=entry_id)
        entry.delete()
        return HttpResponseRedirect(reverse('learning_logs:topics'))
    except Topic.DoesNotExist:
        return HttpResponseNotFound("Topic not exist")

Onenot/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles%}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css  " type="text/css">
</head>
<body style="background:silver">
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>

</p>
{% block content %}{% endblock content %}
<!--Блок с именем content резервирует место; информация, попадающая в блок content, будет определяться дочерним шаблоном.-->

</body>
</html>

Onenot/learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Edit entry</p>
<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>save changes</button>
</form>
{% endblock content %}
</body>
</html>

Onenot/learning_logs/templates/learning_logs/includes/some_html.html
{% block content %}
<p>Блок который подключается при помощи include.</p>
{% endblock content %}

Onenot/learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Learning_logs</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're
    learning about.</p>
{%include "learning_logs/includes/some_html.html "%}
{%include "learning_logs/includes/some_html.html "%}
{% endblock content %}
</body>
</html>

Onenot/learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
</form>
{% endblock content %}
</body>
</html>

Onenot/learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New_topic</title>
</head>
<body>
{% extends "learning_logs/base.html" %}
{% block content %}
<p>Add a new topic:</p>
<form action="{% url 'learning_logs:new_topic' %}" method='post'>
<!--    Аргумент action сообщает серверу, куда передавать данные, отправленные формой; в данном случае данные-->
<!--    возвращаются функции представления new_topic().Аргумент method приказывает браузеру отправить данные в запросе типа POST.-->
    {% csrf_token %}
    <!--защита от несанкционнированного взлома к серверу-->
    {{ form.as_p }}
    <!--создание поля для ввода данных-->
    <button name="submit">add topic</button><!--создание кнопки для отправки данных-->
</form>
{% endblock content %}
</body>
</html>

Onenot/learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'learning_logs/base.html' %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
        <p>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
        </p>
        <p>
            <a href="{% url 'learning_logs:del_entry' entry.id %}">delete entry</a>
        </p>
    </li>
    {% empty %}
    <li>
        There are no entries for this topic yet.
    </li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
<p><a href="{% url 'learning_logs:del_topic'  topic.id %}">delete topic</a></p>

{% endblock content %}
</body>
</html>

Onenot/learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
{%extends "learning_logs/base.html"%}
{% block content %}
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}
</body>
</html>